"""Third commit

Revision ID: 8e2813ba2f18
Revises: e6c52b773829
Create Date: 2021-10-24 18:03:21.289000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2813ba2f18'
down_revision = 'e6c52b773829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
