"""Fourth commit

Revision ID: e30e6fab6786
Revises: 8e2813ba2f18
Create Date: 2021-10-24 18:10:45.604000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30e6fab6786'
down_revision = '8e2813ba2f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('fr0m_id', sa.Integer(), nullable=True))
    op.add_column('transfer', sa.Column('to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer', 'user', ['fr0m_id'], ['id'])
    op.create_foreign_key(None, 'transfer', 'wallet', ['to_id'], ['id'])
    op.add_column('wallet', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wallet', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.drop_column('wallet', 'owner_id')
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.drop_column('transfer', 'to_id')
    op.drop_column('transfer', 'fr0m_id')
    # ### end Alembic commands ###
