"""Second commit

Revision ID: e6c52b773829
Revises: 8f29b03f0c5b
Create Date: 2021-10-24 18:02:16.305000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c52b773829'
down_revision = '8f29b03f0c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
